### ISSUE TITLE
[TRACKER] Customer support related PR tracker for Intel devices

### ISSUE THREAD

**Issue by delock** [microsoft/Megatron-DeepSpeed#446]
This issue acted as a PR tracker to Intel customer support related PRs. The purpose is to get understanding of what each PR does and how important are they compared to other customer support related PRs. This also help us to aware of merged PRs and PRs progress.

o	Model Pretrain Enable
- [ ]	Support Llama2Tokenizer: https://github.com/microsoft/Megatron-DeepSpeed/pull/375
o	FineTune
- [ ]	Supervised Fine-tuning for HugginFace pretrained weight.: https://github.com/microsoft/Megatron-DeepSpeed/pull/318
- [ ]	[LLaMa] Adding support converting checkpoint from mds to hf: https://github.com/microsoft/Megatron-DeepSpeed/pull/432
- [ ]	[Finetune] enable converting checkpoints without optimizer state generation: https://github.com/microsoft/Megatron-DeepSpeed/pull/424
o	Ulysess
- [ ]	ds-sequence-parallel(ulysses) for rope.: https://github.com/microsoft/Megatron-DeepSpeed/pull/392
- [ ]	support split qkv linear and sp overlap comm: https://github.com/microsoft/Megatron-DeepSpeed/pull/415
o	Others
- [ ]	fix reshape for split qga: https://github.com/microsoft/Megatron-DeepSpeed/pull/307
- [ ]	add RMSnorm torch fallback path: https://github.com/microsoft/Megatron-DeepSpeed/pull/312
- [ ]	collect grad_norm for non pipeline path: https://github.com/microsoft/Megatron-DeepSpeed/pull/370
- [ ]	[Wandb] Refine wandb logging function: https://github.com/microsoft/Megatron-DeepSpeed/pull/416
- [ ]	[Bug] Fix crash when logging optimizer state to tensorboard: https://github.com/microsoft/Megatron-DeepSpeed/pull/417
- [ ]	[wandb] disable wandb more gracefully: https://github.com/microsoft/Megatron-DeepSpeed/pull/422
